global:
  scrape_interval: 5s # Mudei para 5s para você ver os resultados mais rápido nos testes
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api_gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api_gateway:8000']
        labels:
          service: 'api_gateway'
  
  - job_name: 'ia_workers'
    metrics_path: '/metrics'
    static_configs:
      # AQUI ESTÁ A CORREÇÃO: Listamos cada réplica individualmente
      - targets: 
          - 'ia_worker_1:8000'
          - 'ia_worker_2:8000'
          - 'ia_worker_3:8000'
        labels:
          service: 'ia_worker_cluster'